pub const STARKNET_RPC_URL_ENV_VAR: &str = "STARKNET_RPC_URL";
pub const PRIVATE_KEY_ENV_VAR: &str = "STARKNET_PRIVATE_KEY";
pub const KEYSTORE_PATH_ENV_VAR: &str = "STARKNET_KEYSTORE_PATH";
pub const KEYSTORE_PASSWORD_ENV_VAR: &str = "STARKNET_KEYSTORE_PASSWORD";
pub const ACCOUNT_ADDRESS_ENV_VAR: &str = "STARKNET_ACCOUNT_ADDRESS";
pub const IPFS_URL_ENV_VAR: &str = "STARKNET_IPFS_URL";
pub const IPFS_USERNAME_ENV_VAR: &str = "STARKNET_IPFS_USERNAME";
pub const IPFS_PASSWORD_ENV_VAR: &str = "STARKNET_IPFS_PASSWORD";
